name: push_docker

on:
  workflow_run:
    workflows: ["build"]
    branches: [master, dev]
    types: 
      - completed
jobs:
  push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' }}
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release and push to Docker Registry
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' }}
        run: |
          if [[ ${{ env.BRANCH_NAME }} == "master" ]]; then
            export VERSION=$(<version.txt)
            git config user.email "release-ci@weave.works"
            git config user.name "release-ci"
            git tag -a v$VERSION -m "Policy Agent v$VERSION release" 
            git push -u origin v$VERSION
          fi

          if [[ ${{ env.BRANCH_NAME }} == "dev" ]]; then
            export VERSION=dev
          fi

          make push@magalixcorp tag-file=new-tag version-file=new-version VERSION=$VERSION
