name: push_docker

on:
  workflow_run:
    workflows: ["build"]
    branches: [master, dev]
    types: 
      - completed
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release and push to Docker Registry
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | tr / -)
          if [[ ${BRANCH_NAME} == "master" ]]; then
            export VERSION=$(<version.txt)
            git config user.email "release-ci@weave.works"
            git config user.name "release-ci"
            git tag -a v$VERSION -m "Policy Agent v$VERSION release" 
            git push -u origin v$VERSION
          fi

          if [[ ${BRANCH_NAME} == "dev" ]]; then
            export VERSION=dev
          fi

          make push@weaveworks tag-file=new-tag version-file=new-version VERSION=$VERSION
